version: '3'
services:
  innersource_ui:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        CLIENT_ID: ${CLIENT_ID}
        API_URL: ${API_URL}
        GITHUB_DOMAIN: ${GITHUB_DOMAIN}
        GRAPH_API_URL: ${GRAPH_API_URL}
    ports:
    - 80:80
    env_file:
      - .env

